# Generated by Django 4.2.1 on 2023-05-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('gender', models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.brand')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.colour')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.country')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
