# Generated by Django 4.2.1 on 2023-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_brand_id_alter_colour_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
